<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<style>
    ul#toolbar {
        font-weight: bold; 
        padding: 3px 10px 3px 3px;
        background-color: #aa3a2f;
        
    }
    
    ul#toolbar li {
        margin-right: 15px; 
        display: inline-block;
    }
    
    ul#toolbar li a {
        display: block; 
        padding: 4px 10px; 
        cursor: pointer; 
        color: #fff;
        border: 1px solid #f6f6f6;
        font-size: 14px;
    }
    ul#toolbar li a:hover, a.active {
        background-color: #333;
    }
    
    ul#toolbar li h3 {
        font-size: 14px;
        color: #fff; 
        padding: 5px 10px; 
        font-weight: bold; 
        margin-bottom: 0;
        border: 1px solid #f6f6f6;
        background-color: #333;
    }
    
</style>
<style>
.rest_suggs ul .sugg:hover, .rest_suggs ul .selected {
    background-color: rgba(150, 127, 127, 0.7) !important;
    transition: 0.2s all ease;
}
    ul#toolbar {
        font-weight: bold; 
        padding: 3px 10px 3px 3px;
        background-color: #aa3a2f;
        
    }
    
    ul#toolbar li {
        margin-right: 15px; 
        display: inline-block;
    }
    
    ul#toolbar li a {
        display: block; 
        padding: 4px 10px; 
        cursor: pointer; 
        color: #fff;
        border: 1px solid #f6f6f6;
        font-size: 14px;
    }
    ul#toolbar li a:hover, a.active {
        background-color: #333;
    }
    
    ul#toolbar li h3 {
        font-size: 14px;
        color: #fff; 
        padding: 5px 10px; 
        font-weight: bold; 
        margin-bottom: 0;
        border: 1px solid #f6f6f6;
        background-color: #333;
    }
} 
</style>
<style>
.textdisable{
        -webkit-touch-callout: none;
-webkit-user-select: none;
-khtml-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
    }
    .slider-serach-bar h1 {
        color: #ffffff;
        margin: 10px;
        text-align: center;
        font-size: 33px;
        text-transform: none;
    } 
    .location{
        float: left;
        padding: 14px;
        font-size: 18px;
        background-color: #fff;
        cursor: pointer;
    }
    .slider-serach-bar .input-box input {
        border-radius: 0;
        height: 55px;
        padding-right: 165px;
        width: 79%;
    }
    @media only screen and (max-width: 400px){
    .headingtop {
        margin-top: -229px !important ;
        text-align: center;
    }
}   
@media only screen and (max-width: 500px){
    .headingtop {
        margin-top: -223px !important ;
        text-align: center;
    }
}
@media only screen and (max-width: 800px) {
    .slider-serach-bar .input-box input {
        border-radius: 0;
        height: 55px;
        padding-right: 165px;
        width: 78%;
    }
}
@media only screen and (max-width: 581px) {
    .slider-serach-bar .input-box input {
        border-radius: 0;
        height: 55px;
        padding-right: 165px;
        width: 73%;
    }
}
@media only screen and (max-width: 640px) {
    .slider-serach-bar .input-box input {
        border-radius: 0;
        height: 55px;
        padding-right: 0px;
        width: 64%;
    }
}

@media only screen and (max-width: 600px) {
    .slider-serach-bar .input-box input {
        border-radius: 0;
        height: 55px;
        padding-right: 0px;
        width: 66%;
    }
}
@media only screen and (max-width: 500px) {
    .slider-serach-bar .input-box input {
        border-radius: 0;
        height: 55px;
        padding-right: 0px;
        width: 70%;
    }
}
@media only screen and (max-width: 600px) {
    .slider-serach-bar .input-box input {
        border-radius: 0;
        height: 55px;
        padding-right: 0px;
        width: 69%;
    }
}
@media only screen and (max-width: 460px) {
    .slider-serach-bar .input-box input {
        border-radius: 0;
        height: 55px;
        padding-right: 0px;
        width: 62%;
    }
}
@media only screen and (max-width: 430px){
    .slider-serach-bar .input-box input {
        border-radius: 0;
        height: 55px;
        padding-right: 0px;
        width: 62%;
    }
}
    }
}

@media only screen and (max-width: 320px){
.slider-serach-bar .input-box input {
    border-radius: 0;
    height: 47px;
    padding-right: 0px;
    width: 60%;
}
}
@media only screen and (max-width: 420px) {
    .slider-serach-bar .input-box input {
        border-radius: 0;
        height: 55px;
        padding-right: 0px;
        width: 61%;
    }
}
@media only screen and (max-width: 393px) {
    .location {
        float: left;
        padding: 14px;
        font-size: 13px;
        background-color: #fff;
        cursor: pointer;
    }

    .slider-serach-bar .input-box input {
        border-radius: 0;
        height: 47px;
        padding-right: 0px;
        width: 65%;
    }
}

@media only screen and (max-width: 320px){
.slider-serach-bar .input-box input {
    border-radius: 0;
    height: 47px;
    padding-right: 0px;
    width: 60%;
}
}
.location {
    float: left;
    padding: 8px;
    font-size: 16px;
    /* background-color: black; */
    cursor: pointer;
    background-color: #aa3a2f;
}
</style>
<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    design
 * @package     base_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
//echo get_class($this);
$vendorsArray = $this->getVendorCollection();

$vendors = $vendorsArray['vendor'];
if ($vendors)
    $vendors->addAttributeToSort('sponsored', 'desc');
$distance = $vendorsArray['distance'];
//	print_r($distance); die("jkg");
$helper = Mage::helper('csmarketplace/tool_image');
$title = Mage::getStoreConfig('ced_vshops/general/vshoppage_title', Mage::app()->getStore()->getId()) ? Mage::getStoreConfig('ced_vshops/general/vshoppage_title', Mage::app()->getStore()->getId()) : "CsMarketplace";
// banner
$width = (int) Mage::getStoreConfig('ced_vshops/general/vshoppage_banner_image_width', Mage::app()->getStore()->getId());
$height = (int) Mage::getStoreConfig('ced_vshops/general/vshoppage_banner_image_height', Mage::app()->getStore()->getId());
$img = Mage::getStoreConfig("ced_vshops/general/vshoppage_banner", Mage::app()->getStore()->getId()) ? "ced/csmarketplace/" . Mage::getStoreConfig("ced_vshops/general/vshoppage_banner", Mage::app()->getStore()->getId()) : '';
$width = $width ? $width : 800;
$height = $height ? $height : 200;
?>
<?php if (Mage::helper('csmarketplace/acl')->isEnabled()) { ?>


    
    <?php
    $currentUrl = Mage::getUrl('*/*/*');
    $queries = Mage::app()->getRequest()->getQuery();
    $sortParams = [
//        'entity_id' => "Entity ID", 
        'public_name' => "Vendor Name", 
        'distance' => "Distance", 
        'delivery_fee' => 'Delivery Fee',  
//        'min_freeship', 
//        'created_at'
    ];
    ?>
    <ul id="toolbar">
    <?php
    $currentSortBy = isset($queries['sortby']) ? $queries['sortby'] : 'distance';
    $currentSortDir = isset($queries['sortdir']) ? $queries['sortdir'] : 'asc';
    ?>
        <li><h3>Sort By: </h3></li>
    <?php
    foreach ($sortParams as $sortBy => $sortValue) {
        if ($currentSortBy == $sortBy) {
            $queries['sortdir'] = ($queries['sortdir'] === 'asc') ? 'desc' : 'asc';
        } else {
            $queries['sortdir'] = $currentSortDir;
        }
        $queries['sortby'] = $sortBy;
    ?>    
        <li>
            <a href="<?php echo $currentUrl . '?' . http_build_query($queries); ?>" <?php if ($currentSortBy == $sortBy) { echo 'class="active"'; } ?>  >
                   <?php echo $sortValue ?>&nbsp;&nbsp;
                   <?php if ($currentSortBy == $sortBy) { ?>
                   <span style="font-weight: 200; font-size: 14px;">
                   <?php if($queries['sortdir'] == 'asc') { ?>&DownArrow;
                   <?php } else { ?>&UpArrow;<?php }} ?>
                   </span>
            </a>
        </li>
    <?php
    }
    ?>
    </ul>
     

<?php

/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$addressPlaceholder = Mage::getStoreConfig('lod_configs/address_search_bar/placeholder');
Mage::getSingleton('core/session')->unsSearchaddress();
if (strpos($currentUrl, 'vendor-shop') === false) {
	?>
	
	<form id="search_forms" action="<?php echo $this->getUrl('csmarketplace/vshops/index'); ?>" method="get">
   
	  <div class="input-box"  id=rests_suggets>
      <b> <?php // echo $this->__('Enter your Address in the search bar');?></b>
      <span style="color:white;" id="locationbar" class="location textdisable"><i class="fa fa-location-arrow" aria-hidden="true"></i><span style="color:white;" class="">Locate Me</span></span>
        <input style="border-radius: 0px; width:60%;" name="rest" id="rest_names1" type="search" value="<?php echo $getSession = Mage::getSingleton('core/session')->getSearchaddress(); ?>" class="search input-text required-entry" autocomplete="off" 
         placeholder="<?php echo $this->quoteEscape($this->__($addressPlaceholder)) ?>" />
        <button style="border-radius: 5px;" id="findfood" type="submit" title="<?php echo $this->quoteEscape($this->__('Lets Find Food')) ?>" class="button search-button"><span><span><?php echo $this->__('Lets Find Food') ?></span></span></button>
    </div>
        <script type="text/javascript">
      //<![CDATA[
        var dataForm = new VarienForm('search_form', true);
     
    //]]>
        </script>
      <!--  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyCITgXxySbOP2A0OWtAZQ803TIGGgUpUEA" type="text/javascript"></script>
        <script>
        google.maps.event.addDomListener(window, 'load', initMap);
        function initMap() {
        	  var input = document.getElementById('rest_names1');
            var autocomplete = new google.maps.places.Autocomplete(input);
            google.maps.event.addListener(autocomplete, 'place_changed', function () {
                var place = autocomplete.getPlace();
                document.getElementById('findfood').click();
            });
        }
            </script> -->
    
</form>
	
	<?php 
}
else{?>

<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="input-box">
        <label for="search"><?php echo $this->__('Search:') ?></label>
        <input id="search" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text required-entry" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" placeholder="<?php echo $this->__('Search entire store here...') ?>" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button search-button"><span><span><?php echo $this->__('Search') ?></span></span></button>
    </div>

    <div id="search_autocomplete" class="search-autocomplete"></div>
    <script type="text/javascript">
    //<![CDATA[
        var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
        searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
    //]]>
    </script>
</form>
<?php 
	
}

?>


<!--<script>
  jQuery(document).ready(function() {
    jQuery("#rest_names1").keypress(function () {
     var Address = jQuery("#rest_names1").val(); 
     jQuery.ajax({
        url: "<?php //echo Mage::getUrl('applink/index/Addressserch/'); ?>",
        type: "POST",
        data: { "address": Address },
        success: function(data) {
            //alert(data);
          //jQuery('').html(data);
        }
      });
    });
  });
</script>   -->

<script>
var req = null;
var index = 1;
jQuery('input').keyup(function(e)
{  
	//var key = e.keyCode;
 // if ( key != 40 && key != 38 )
  //{
//jQuery("#rest_names").keyup(function(){
    window.index= 1;
	var string = jQuery("#rest_names1").val();
	if (req != null) req.abort();
	if(string.length > 1){
            
		req = jQuery.ajax({
			type: "POST",
			url: "<?php echo Mage::getUrl('csmarketplace/search/suggestion'); ?>",
			data: {name: string},
			success: function(html){
				if(html.length !=0)
				{
					jQuery(".rest_suggs").remove();
					var newDiv = jQuery(document.createElement('div')).attr("class", "rest_suggs").attr("style", "border: 1px solid #bbafa0;");
					newDiv.html(html);				
					newDiv.appendTo("#rests_suggets");
			    }
				/* else{
					   jQuery(".rest_suggs").remove();
					} */
				
				
			}
		});
	}else{
		jQuery(".rest_suggs").remove();
	}	
 //});
  //}
});
function pickval(id) {
jQuery("#rest_names1").val(id);
	jQuery(".rest_suggs").remove();
	jQuery("#search_forms").submit();
}	

var listItems = jQuery('.sugg');

jQuery('input').keydown(function(e)
{
    var key = e.keyCode;
    var  selected = jQuery('.nav li.selected').text();
   
    var  current;

    if ( key != 40 && key != 38 ) return;

    jQuery('.nav li.selected').removeClass('selected');

    if ( key == 40 ) // Down key
    {
    	var count = jQuery("#rests_suggets ul").children().length;
    	
    	if(index == count)
    	{
    		window.index= 0;
        }
        if ( ! selected.length ) {
           
            current = "ul.nav li:nth-child(1)";
            //jQuery( "ul.nav li:nth-child(1)" ).css( "color", "red" );
         //   console.log(current);
         //   alert(current+"if");
        }
        else {
           // alert(index);
            window.index= index+1;
            
            current = "ul.nav li:nth-child("+index+")";
           
        }
    }
    else if ( key == 38 ) // Up key
    {  
        
    	var count = jQuery("#rests_suggets ul").children().length;
    	if(index != 1)
    	{
    		window.index = index-1;
         }
    	if(index == 1)
    	{
    		window.index = count;
        }
    	
        if (!selected.length) {
        	current = "ul.nav li:last-child()";
        }
        else {
        	current = "ul.nav li:nth-child("+index+")";
        }
    }
   //alert(jQuery(current).text()+"end");
    jQuery(this).val( jQuery(current).addClass('selected').text());
});


    </script>










    <?php 
    if (!$vendors || !$vendors->count()) {
    ?>
    <div class="remove_vendors_wrap">
        <p><?php echo $this->__('Sorry!! No Records available.') ?></p>
        <p><a href='#' style="color: #333; cursor: pointer"><i class="fa fa-hand-o-up"></i>Change Location</a></p>
    </div>
    <?php
    } else {
        $url = $this->getBaseUrl();
        if (!Mage::registry('got_geo_codes')) {
    ?>
    <div class="">
        <b>
            <p class="note-msg" style="font-size: 12px">
                Could not get geo codes but you can try these.
            </p>
        </b>
    </div>
    <?php
        } else { 
    ?>
    <div class="">
        <b><font size="3px"><p class="note-msg"><?php echo $vendors->count() . " restaurants deliver to " . $this->getRequest()->getParam('rest') . ". <a href='$url'>Change Location</a> " ?></p></font></b>
    </div>
    <?php
        }
    ?>


        <?php
        $width = (int) Mage::getStoreConfig('ced_vshops/general/list_image_width', Mage::app()->getStore()->getId());
        $height = (int) Mage::getStoreConfig('ced_vshops/general/list_image_height', Mage::app()->getStore()->getId());
        $width = $width ? $width : 135;
        $height = $height ? $height : 135;
        ?>
        <div class="vendor_list_page">

            <?php
            $i = 0;
            $day = Mage::getSingleton('core/date')->date('w');
            foreach ($vendors as $vendor) {
                for ($j = 0; $j < count($distance); $j++) {
                    if ($distance[$j]['id'] == $vendor->getEntityId()) {
                        $diff = $distance[$j]['distance'];
                    } else {
                        continue;
                    }
                }


                if ($day == 0) {
                    $value = $vendor->getSunCloseTime();
                    $value = explode(',', $value);
                    $value = implode(':', $value);

                    $Openvalue = $vendor->getSunOpenTime();
                    $Openvalue = explode(',', $Openvalue);
                    $Openvalue = implode(':', $Openvalue);
                } elseif ($day == 1) {
                    $value = $vendor->getMonCloseTime();
                    $value = explode(',', $value);
                    $value = implode(':', $value);

                    $Openvalue = $vendor->getMonOpenTime();
                    $Openvalue = explode(',', $Openvalue);
                    $Openvalue = implode(':', $Openvalue);
                } elseif ($day == 2) {

                    $value = $vendor->getTueCloseTime();
                    $value = explode(',', $value);
                    $value = implode(':', $value);

                    $Openvalue = $vendor->getTueOpenTime();
                    $Openvalue = explode(',', $Openvalue);
                    $Openvalue = implode(':', $Openvalue);
                } elseif ($day == 3) {

                    $value = $vendor->getWedCloseTime();
                    $value = explode(',', $value);
                    $value = implode(':', $value);

                    $Openvalue = $vendor->getWedOpenTime();
                    $Openvalue = explode(',', $Openvalue);
                    $Openvalue = implode(':', $Openvalue);
                } elseif ($day == 4) {
                    $value = $vendor->getThuCloseTime();
                    $value = explode(',', $value);
                    $value = implode(':', $value);

                    $Openvalue = $vendor->getThuOpenTime();
                    $Openvalue = explode(',', $Openvalue);
                    $Openvalue = implode(':', $Openvalue);
                } elseif ($day == 5) {
                    $value = $vendor->getFriCloseTime();
                    $value = explode(',', $value);
                    $value = implode(':', $value);

                    $Openvalue = $vendor->getFriOpenTime();
                    $Openvalue = explode(',', $Openvalue);
                    $Openvalue = implode(':', $Openvalue);
                } elseif ($day == 6) {
                    $value = $vendor->getSatCloseTime();
                    $value = explode(',', $value);
                    $value = implode(':', $value);

                    $Openvalue = $vendor->getSatOpenTime();
                    $Openvalue = explode(',', $Openvalue);
                    $Openvalue = implode(':', $Openvalue);
                }
                ?><ol>
                    <li class="logo">
                        <a href="<?php echo $vendor->getVendorShopUrl() ?>" title="<?php echo $this->stripTags($vendor->getPublicName(), null, true) ?>" class="product-image vendor-logo-image"><img src="<?php echo $helper->init($vendor->getData('company_logo'))->keepFrame(false)->resize($width, $height); ?>" alt="<?php echo $this->stripTags($vendor->getPublicName(), null, true) ?>" /></a>
                    </li>
                    <li class="name"><a href="<?php echo $vendor->getVendorShopUrl() ?>" title="<?php echo $this->stripTags($vendor->getPublicName(), null, true) ?>"<font size="4px"><?php echo $vendor->getPublicName(); ?></font></a><span class="value"> <?php echo $vendor->getAddress(); ?></span>
                        <?php $rest = $this->getRequest()->getParam('rest');
                        if ($rest) {
                            ?>
                            <span><?php echo $this->__("Approx. Distance: ");
                                echo $diff;
                            ?></span>
                        <!--<p>Sql Calulated Distance: <?php // echo $vendor->getData('distance'); ?></p>-->
                        <?php } ?> 
                    </li>
                    <li class="open_time">
                        <?php $todayPrefix = date("Y-m-d", Mage::getModel('core/date')->timestamp(now())); ?>
                        <label><?php echo __('Starts At'); ?></label>
                        <span class="value">
                            <?php echo nl2br(date("Y-m-d h:i:s a", strtotime($todayPrefix . " " . $Openvalue))); ?>
                        </span>
                    </li>
                    <?php
                    $openingAt = intval(substr($Openvalue, 0, 2));
                    $closingAt = intval(substr($value, 0, 2));
                    $diff = $closingAt - $openingAt;
                    ?>
                    <li class="open_time">
                        <label><?php echo __('Open Until'); ?></label>
                    <?php if ($diff <= 0) { ?>
                        <span class="value">
                            <?php echo nl2br(date("Y-m-d h:i:s a", strtotime(date("Y-m-d h:i:s a", strtotime($todayPrefix . " " . $value)) . " +24 hour"))); ?>
                        </span>
                    <?php } else { ?>
                        <span class="value">
                            <?php echo nl2br(date("Y-m-d h:i:s a", strtotime($todayPrefix . " " . $value))); ?>
                        </span>
                    <?php } ?>
                    </li>
                    <?php
                    if ($diff <= 0) {
                        $value = date("Y-m-d h:i:s", strtotime($todayPrefix . " " . $value)) . " +24 hour";
                    } else {
                        $value = date("Y-m-d h:i:s", strtotime($todayPrefix . " " . $value));
                    }
                    ?>
                    <!--<li  class="open_time" <?php if ($diff <= 0) { ?>style="background: transparent" <?php } ?>>
                      <?php
                        $formatedOpeningTime = date('Y-m-d H:i:s', strtotime($todayPrefix . " " . $Openvalue));
                        $formatedClosingTime = date('Y-m-d H:i:s', strtotime($value));
                        $now = Mage::getModel('core/date')->timestamp(now());
                        $diff1 = strtotime(date("Y-m-d H:i:s", $now)) - strtotime($formatedOpeningTime);
                        $diff2 = strtotime($formatedClosingTime) - strtotime(date("Y-m-d H:i:s", $now));
                        $isOpen = ( ($diff1 >= 0) && ($diff2 >= 0) ) ? "OPEN" : "CLOSED";
                        ?>
                        <label><?php echo $isOpen; ?></label>
                        <span class="value"><?php echo date("Y-m-d h:i:s a", $now); ?></span>
                    </li> -->

                    <li class="rating"><?php echo __('Rating'); ?><span class="value"> <?php echo $this->getReviewsSummaryHtml($vendor); ?></span> </li>
                    <li class="min_amount"><?php echo __('Minimum Order Value'); ?><span class="value"> <?php
                if ($vendor->getMinOrderAmount()) {
                    echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
                }echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . $vendor->getMinFreeship();
            ?></li>
                    <li class="wait_time"><?php echo __('Wait Time'); ?><span class="value"> <?php echo $vendor->getDeliveryTime(); ?></li>
                    <li class="delivery">
                            <?php echo __('Delivery'); ?>
                        <span class="value">
                            <?php
                            if ($vendor->getDeliveryFee()) {
                                echo $vendor->getDeliveryFeeInRadius($diff);
                            }
                            ?>
                        </span>
                    </li>
                    <li class="view_product"><a href="<?php echo $vendor->getVendorShopUrl() ?>"></a></li>
                </ol>
                <?php
            }
            ?>
        </div>
    <?php
    }
}
?>

<script>
jQuery(document).ready(function(){
    jQuery('#locationbar').on('click', function() { 
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showLocation);
    } else { 
        jQuery('#location').html('Geolocation is not supported by this browser.');
    }
    }); 
});

function showLocation(position) {
    var latitude = position.coords.latitude;
    var longitude = position.coords.longitude;
    jQuery.ajax({
        type:'POST',
        url:"<?php echo Mage::getUrl('lodmarketplace/vshops/getlocation/'); ?> ",
        data:'latitude='+latitude+'&longitude='+longitude,
        success:function(msg){
            if(msg){
               jQuery("#rest_names1").val(msg);
            }else{
               jQuery("#rest_names1").val('');
            }
        }
    });
}
</script>