<style>
	.slider-block {
		top: -150px !important;
	}

	@media (max-width: 767px){
		.slider-block {
			top: -297px !important;
		}
	}

	@media only screen and (max-width: 991px){
		.slider-block {
			margin: 0px 0;
			top: 0;
		}
	}
	.breadcrumbs {
		Display: none;
	}
	.headingtop {
		margin-top: 81px;
		text-align: center;
	}
	
	@media only screen and (max-width: 1100px) and (min-width: 991px){
		.headingtop {
			margin-top: 19px;
			text-align: center;
		}
	}
	@media only screen and (max-width: 991px) and (min-width: 770px){
		.headingtop {
			margin-top: -125px;
			text-align: center;
		}
	}

	@media only screen and (max-width: 767px){
		.headingtop {
			margin-top: -275px;
			text-align: center;
		}
	}
	@media only screen and (max-width: 767px){
		.cms-page-view .std p, .cms-no-route .std p {
			color: #464646;
			font-size: 10px;
			line-height: 24px;
		}
	}
	.storelogo{
		width: 100%;
		height: 150px;
		border-radius: 5px;
	}
	@media only screen and (max-width: 767px){
		.storelogo{
			width: 100%;
			height: 100px;
			border-radius: 5px;
		}
	}
	.post-item:hover {
		outline: 0px solid transparent;
		padding: 2px 2px;
		border: 1px solid #150b09;
	}
</style>
<?php 
error_reporting(E_ALL);
ini_set('display_errors', 1);
$region = "Arbutus";
$vendorCollection = Mage::getResourceModel('csmarketplace/vendor_collection')
->addAttributeToSelect('*')
->addAttributeToSelect(array(
	'store_latitude',
	'store_longitude',
	'delivery_radius'
	), 'left');
$vendorCollection->joinTable(
	array('vshop'=> 'mg_ced_csmarketplace_vendor_shop'), 
	'vendor_id=entity_id', 
	array('shop_disable'=>'shop_disable')
	);
$vendorCollection->addFilterToMap('distance', 'e.distance');
$vendorCollection->addFilterToMap('shop_disable', 'vshop.shop_disable');
$vendorCollection->addFieldToFilter('shop_disable', array('eq' => 1));
$validIds = [];
foreach ($vendorCollection->getData() as $val) {
            $validIds [] = $val['entity_id'];
}
asort($validIds);
//$vendorCollection->addAttributeToFilter('entity_id', array('in' => $validIds));
?>
         <?php  
    $store_type = array(
    47    => "American",
    36    => "Bakery",
    40    => "BBQ",
    38    => "Breakfast",
    22    => "Burgers",
    35    => "Cafe",
    41    => "Canadian",
    31    => "Caribbean",
    15    => "Chicken",
    4     => "Chinese",
    39    => "Deli",
    33    => "Desserts",
    29    => "Fish",
    30    => "French",
    16    => "Greek",
    14    => "Halal",
    43    => "Healthy",
    18    => "Indian",
    12    => "Indian Pakistani",
    3    => "Italian",
    34    => "Jamaican",
    32    => "Japanese",
    45    => "Labanese",
    37    => "Maxican",
    17    => "Mediterranean",
    19    => "Middle Eastern",
    13    => "Pizza",
    42    => "Sandwiches",
    28    => "Sushi",
    25    => "Thai",
    44    => "Vegetarian",
    24    => "Vietnamese",
    46    => "Wings",
);
//print_r($validIds);
$key = array_search('Greek', $store_type);
//echo $key;
         if(count($validIds)) { 
         	foreach($validIds as $venId){
	if($vendor['group']==$key){?>
        <h1 class="headingtop">List of the restaurant who deliver Greek Food</h1>
        <?php } }} ?>
        <div class="row">
        	<?php
        	//echo "<pre>";
        	foreach($validIds as $venId){
        		$vendor = Mage::getModel('csmarketplace/vendor')->load($venId)->toArray();
                if($vendor['group']==$key){
        		//print_r($vendor);
        		if($vendor['is_active']==1){
        			?>
        			<div class="col-lg-3 col-sm-6 col-md-6 col-xs-6">
        				<a href="<?php echo Mage::helper('core/url')->getHomeUrl()."restaurant/". $vendor['shop_url'];?>" >
        					<img class="storelogo"  src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$vendor['company_logo']; ?>"><br/>
        					<p class="storename" style="text-align:left;"><span style="font-weight: bold;"><?php echo $vendor['public_name'];?></span><br/>
        						<?php echo $vendor['address'];?></p>

        					</a>
        				</div>
        				<?php }}}
        				?>
        			</div>

<script>
jQuery(document).ready(function(){
	jQuery('#locationbar').on('click', function() { 
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showLocation);
    } else { 
        jQuery('#location').html('Geolocation is not supported by this browser.');
    }
    }); 
});

function showLocation(position) {
    var latitude = position.coords.latitude;
	var longitude = position.coords.longitude;
	jQuery.ajax({
		type:'POST',
		url:"<?php echo Mage::getUrl('lodmarketplace/vshops/getlocation/'); ?> ",
		data:'latitude='+latitude+'&longitude='+longitude,
		success:function(msg){
            if(msg){
               jQuery("#rest_names1").val(msg);
            }else{
               jQuery("#rest_names1").val('');
            }
		}
	});
}
</script>