<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-catalogsale-products">
        <div class="page-title category-title">
            <h1><?php echo $this->__('Special products') ?></h1>
        </div>
            <?php $suffix = $this->getNameInLayout(); ?>
            <ul class="products-grid row" id="widget-catalogsale-products-<?php echo $suffix; ?>">
            <?php foreach ($_products->getItems() as $_product): ?>
                <li class="item col-xs-12 col-sm-3" itemscope itemtype="http://schema.org/product">
                    <div class="wrapper-hover">
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(228) ?>"  alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/>
                            <?php $_product2 = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                            <div class="label-product">             
                                <?php if($_product2->getData('new')){echo '<span class="new">'.$this->__('New').'</span>';  }?>
                                <?php if($_product2->getData('sale')){echo '<span class="sale">'.$this->__('Sale').'</span>';  }?>
                            </div>
                        </a>
                        <div class="product-info">
                                <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)" itemprop="name"><?php $small_getName = strip_tags($_product->getName());
                                    if (strlen($small_getName) < 25) echo($small_getName);
                                    else { echo mb_substr($small_getName, 0, 25,'UTF-8').'...';} ?></a></p>
                                    <?php echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix) ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        
                             <div class="actions">
                                <?php if($_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?><i class="fa fa-shopping-cart"></i></span></span></button>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" rel="tooltip" class="link-wishlist"><i class="fa fa-heart"></i> <span><?php echo $this->__('Add to Wishlist') ?></span> </a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a  title="<?php echo $this->__('Add to Compare') ?> " href="<?php echo $_compareUrl ?>" rel="tooltip" class="link-compare "><i class="fa fa-retweet"></i> <span><?php echo $this->__('Add to Compare') ?></span></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>

                    </div>
                </li>
            <?php endforeach; ?>
            </ul>
            <script type="text/javascript">decorateList('widget-catalogsale-products-<?php echo $suffix; ?>', 'none-recursive')</script>
</div>
<?php endif; ?>
