<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
*
 * @category    design
 * @package     ced_default
 * @author 		CedCommerce Core Team <coreteam@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */ 
 
?>
<style>
	.btn-large-circle {
		border-bottom-left-radius: 15px;
		border-bottom-right-radius: 15px;
		border-top-left-radius: 15px;
		border-top-right-radius: 15px;
		font-size: 12px;
		height: 34px;
		line-height: 1.42857;
		padding-bottom: 6px;
		padding-left: 3px;
		padding-right: 3px;
		padding-top: 6px;
		text-align: left;
		width: 108px;
	}
</style>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<?php $collection = $this->getPendingVpayments(); 
//echo $collection->getSelect();die;
$params = Mage::getSingleton('core/session')->getData('payment_request_filter');

?>
<div class="row">
<div class="col-md-12" style="margin-top:10px;">
	<div class="panel panel-default">
		<div class="panel-heading col-md-12" style="text-transform: uppercase;font-weight:bold;padding:4px 15px;">
			<div  style="line-height:31px;font-size:17px;display:inline;text-transform: uppercase;">
			<?php echo $this->__('Pending Amount(s)'); ?>
			</div>
         </div>
 	<div class="panel-body">
 	<div class="col-md-12" style="margin-top:10px;">
<form id="payment_form"
	action=""
	enctype="multipart/form-data" method="post">
	<div class="vendor-button-set buttons-set filter_button">
	<?php if(count($collection)>0){ ?>
		<div class="col-md-4 export-button" style="padding-left:0;">
		</div>
		<div class="col-md-8 filter-buttons" style="margin-left:0;padding-right:0;text-align:right;">
	<?php }
	else{ 
		 ?>
		<div class="col-md-12" style="margin-left:0;padding-right:0;margin-bottom:5px;text-align:right;">
	<?php }?>
		<button  style="margin:2px" onClick="filterPayment(0);" class="button btn btn-info uptransform " title="<?php echo $this->__('Filter') ?>" type="submit" id="Filter"	>
			<span><span><?php echo $this->__('Filter') ?></span></span>
		</button> 
		<button  style="margin:2px" onClick="filterPayment(1);" class="button btn btn-info uptransform" title="<?php echo $this->__('Reset Filter') ?>" type="button" id="Filter"	>
			<span><span><?php echo $this->__('Reset Filter') ?></span></span>
		</button>
		</div>
		
	</div>	
	



<div style="clear:both;"></div>
<br/>
<?php echo $this->getPagerHtml(); ?>
<div style="clear:both"></div>
<div class="order-items order-details table-responsive">
		<table id="my-products-table" class="table table-bordered table-hover table-striped">
	    <col width="1" />
		<col width="1" />
		<col width="1" />
	    <col width="1" />
	    <col width="1" />
		<thead>
			<tr style="background-color: #2c3b41;">
				<td colspan="3" style="text-align: left; vertical-align: middle; border-right-style: none; color: #fff;">
					<a style="cursor: pointer; color: #fff;" onclick="jced('.payment_request_checkbox').prop('checked', true);"><?php echo $this->__('Select All'); ?></a> / <a style="cursor: pointer; color: #fff;" onclick="jced('.payment_request_checkbox').prop('checked',false);"><?php echo $this->__('Unselect All'); ?></a>
				</td>
				<td colspan="2" style="text-align: right; vertical-align: middle; border-left-style: none;">
					<button  style="margin:2px" onClick="massPayRequest(0);" class="button btn btn-info uptransform " title="<?php echo $this->__('Filter') ?>" type="button" id="request_selected"	>
						<span><span><?php echo $this->__('Mass Request Payment') ?></span></span>
					</button> 
				</td>
			</tr>
			<tr style="background-color: #f5f5f5;">
				<th class="head"></th>
				<th class="head"><?php echo $this->__('Order Date') ?></th>
				<th class="head"><?php echo $this->__('Order Id') ?></th>
				<th class="head"><?php echo $this->__('Pending Amount') ?></th>
				<th class="head a-left"><?php echo $this->__('Action') ?></th>
			</tr>
         	<tr class="filter">
				<th class="filter"></th>
				<th class="filter">
					<div class="list_filter">
					<img src="<?php echo $this->getSkinUrl('images/calendar.gif') ?>" class="v-middle" id="date_from_trig" />
					<input type="text" id="created_at_from" name="created_at[from]" class="form-control" value="<?php echo (isset($params['created_at']['from']) && urldecode($params['created_at']['from'])!="")?urldecode($params['created_at']['from']):""; ?>" /></div>
					<div class="list_filter">
					<img src="<?php echo $this->getSkinUrl('images/calendar.gif') ?>" class="v-middle" id="date_to_trig" />
					<input type="text"  id="created_at_to" name="created_at[to]"  class="form-control" value="<?php echo (isset($params['created_at']['to']) && urldecode($params['created_at']['to'])!="")?urldecode($params['created_at']['to']):""; ?>"  /></div>
				</th>
	            <th class="filter">
					<div class="list_filter"><input  type="text"  onUnfocus="filterPayment(0);" class="form-control filter" name="order_id"  value="<?php echo (isset($params['order_id']) && urldecode($params['order_id'])!="")?urldecode($params['order_id']):""; ?>"  /></div>
				</th> 
				<th class="filter">
					<div class="list_filter"><input type="text" name="net_amount[from]" class="form-control filter" value="<?php echo (isset($params['net_amount']['from']) && urldecode($params['net_amount']['from'])!="")?urldecode($params['net_amount']['from']):""; ?>"  /></div>
					<div class="list_filter"><input type="text" name="net_amount[to]" class="form-control filter" value="<?php echo (isset($params['net_amount']['to']) && urldecode($params['net_amount']['to'])!="")?urldecode($params['net_amount']['to']):""; ?>"  /></div>
				</th>
	            <th class="filter"></th>
			</tr>
	    </thead>
	    <tbody>
		<?php if(count($collection)>0): ?>
	        <?php $_odd = ''; ?>
	        <?php foreach ($collection as $_payment): ?>
			<?php if($_payment->getCurrency()=='0.0000'){ ?>
			<tr>
				<td><input type="checkbox" name="payment_request[]" class="payment_request_checkbox" value="<?php echo $_payment->getId(); ?>" /></td>
	            <td class="status"><?php echo  Mage::helper('core')->formatDate( $_payment->getCreatedAt() , 'medium', true);	 ?></td>
				<td class="number"><?php echo $_payment->getOrderId() ?></td>     
	            <td class="number"><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol().''.$_payment->getNetAmount();  ?></td>
	     		<td class="a-left view number status">
					<button type="button" class="button btn btn-info uptransform " onClick="massPayRequest(<?php echo $_payment->getId(); ?>);">
						<span><span><?php echo $this->__('Request Payment') ?></span></span>
					</button>
	            </td>
	        </tr>
			<?php }else{ ?>
	        <tr>
				<td><input type="checkbox" name="payment_request[]" class="payment_request_checkbox" value="<?php echo $_payment->getId(); ?>" /></td>
	            <td class="status"><?php echo  Mage::helper('core')->formatDate( $_payment->getCreatedAt() , 'medium', true);	 ?></td>
	            <td class="number"><?php echo $_payment->getOrderId() ?></td>     
	            <td class="number"><?php echo Mage::app()->getLocale()->currency($_payment->getCurrency())->toCurrency($_payment->getNetVendorEarn());  ?></td>
	     		<?php $model = Mage::getModel('csmarketplace/vpayment_requested')->loadByField(array('vendor_id','order_id'),array($this->getVendorId(),$_payment->getId())); ?>
				<td class="a-left view number status">
					<?php if($model && $model->getId()) { ?>
						<?php $statuses = Ced_CsMarketplace_Model_Vpayment_Requested::getStatuses(); ?>
						<?php if(isset($statuses[$model->getStatus()])){ ?>
							<span><span><?php echo $statuses[$model->getStatus()]; ?></span></span>
						<?php } else { ?>
							<span><span><?php echo $this->__('In Processing') ?></span></span>
						<?php } ?>
					<?php } else { ?>
						<button type="button" class="button btn btn-info uptransform " onClick="massPayRequest(<?php echo $_payment->getId(); ?>);">
							<span><span><?php echo $this->__('Request Payment') ?></span></span>
						</button>
					<?php } ?>
				</td>
	        </tr>
			<?php } ?>
	        <?php endforeach; ?>
	    
				<?php else: ?>
				<tr><td colspan="7">
				<div>
				<p><?php echo $this->__('No Transactions Available'); ?></p>
				</div>
		</td></tr>		
			<?php endif ?>
		</tbody>
	</table>
</div>
<?php echo $this->getPagerHtml(); ?>
  </form>
  </div>
  </div>
  </div>
  </div>
  </div>
<script type="text/javascript">decorateTable('my-payments-table');</script>




<style>
.list_filter input{
width:100%;
padding: 2px;
}
#date_from_trig, #date_to_trig{
float:left;
}
#created_at_from, #created_at_to{
width:78%;
}
</style>
<script type="text/javascript">// <![CDATA[
setTimeout(function(){
Calendar.setup({
    inputField : 'created_at_from',
    ifFormat : '%m/%e/%y',
    button : 'date_from_trig',
    align : 'Bl',
    singleClick : true
});

Calendar.setup({
    inputField : 'created_at_to',
    ifFormat : '%m/%e/%y',
    button : 'date_to_trig',
    align : 'Bl',
    singleClick : true
});
}, 500);
// ]]></script>

<script type="text/javascript">

<?php if($this->getRequest()->getActionName()=='index'){ ?>
	filterPayment(2);
  <?php } ?>
  
	jced(document).ready(function(){
	  jced("#payment_form").submit(function() {
				return false;
			});
	});

function massPayRequest(paymentids){
	var params = '';
	if(paymentids==0){
		var checkBoxes;
		checkBoxes = document.getElementsByClassName('payment_request_checkbox');
		for(var i=0; i<checkBoxes.length ; i++){
			if(checkBoxes[i].checked){
				if(params.length == 0){
					params += 'payment_request='+checkBoxes[i].value;
				} else {
					params += ','+checkBoxes[i].value;
				}
			}
		}
	} else {
		params += 'payment_request='+paymentids;
	}
	if(params.length == 0){
		alert('Please Select Amount(s)');
		return false;
	}
	jced('#activity-loading').show();
	new Ajax.Request("<?php 
		$urlParams['_nosid'] = true;
		if(Mage::app()->getStore()->isCurrentlySecure()) {
			$urlParams['_secure'] = true;
		}	
		echo   $this->getUrl('csmarketplace/vpayments/requestPost',$urlParams) ?>?"+params, {
		   method: 'Get',
		   onComplete: function(transport) {
			   jced('.vendor-dashboard').html(transport.responseText);
			   jced('#activity-loading').hide();
		   }
	});
}
function filterPayment(reset){
		var params ;
		if(reset==2)
        	reset=0;
    	jced('#activity-loading').show();
		if(reset==1)
			params ='{reset_filter:1}';
		else
			params = jced("#payment_form").serialize().replace('+','%20');

		new Ajax.Request("<?php 
		$urlParams['_nosid'] = true;
		if(Mage::app()->getStore()->isCurrentlySecure()){
			$urlParams['_secure'] = true;
		}	
		echo   $this->getUrl('csmarketplace/vpayments/requestFilter',$urlParams) ?>", {
           method: 'Post',
           parameters:params,
           onComplete: function(transport) {
               jced('.vendor-dashboard').html(transport.responseText);
               jced('#activity-loading').hide();

           }
       });
   }
   
   
   function setLocation(url){
	   jced('#activity-loading').show();
		new Ajax.Request(url, {
           method: 'Get',
           onComplete: function(transport) {
               jced('.vendor-dashboard').html(transport.responseText);
               jced('#activity-loading').hide();
           }
       });
   }
   
   jced('.pages a').click(function(e){	
		var url = jced(this).attr('href');
		if(url!="#"){
			jced('#activity-loading').show();
			e.preventDefault();
			new Ajax.Request(url, {
	           method: 'Get',
	           onComplete: function(transport) {
	               jced('.vendor-dashboard').html(transport.responseText);
	               jced('#activity-loading').hide();
	           }
	       });
		}
	});
 
</script>