<?php 

/**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsVendorReview
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
  
	if(Mage::getStoreConfig('ced_csmarketplace/vendorreview/activation')){

	$width = $this->getVendorRating();
	$url = Mage::getUrl('csvendorreview/rating/list', array('id'=>$this->getVendorId()));
?>
<div class="block">
    <div class="block-title">
        <strong><span><?php echo $this->__('Vendor Review & Rating') ?></span></strong>
    </div>
    <div class="block-content" style="padding: 10px;">
        <dl id="narrow-by-list2">
            <ul>				
				<?php if($width > 1){ ?>
				<li>
                    <strong><span><?php echo $this->__('Average Rating') ?></span></strong>
                </li>
				<li>
                    <div class="rating-box">
						<div class="rating" style="width:<?php echo $width ?>%;"></div>
					</div>
                </li>
				<li>
                    <a href="<?php echo $url ?>"><?php echo $this->__('Add Your Review') ?></a>
                </li>
				<?php } else {?>
					<li>
						<a href="<?php echo $url ?>"><?php echo $this->__('Be The First To Review') ?></a>
					</li>
                <?php } ?>
            </ul>
        </dl>
    </div>
</div>
<?php } ?>