<?php

/**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Academic Free License (AFL 3.0)
  * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/afl-3.0.php
  *
  * @category    Ced
  * @package     Ced_CsVAttribute
  * @author   	 CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */
?>
<?php
	$this->_vendor = Mage::getModel('csmarketplace/vendor');

  $this->_vendorCollection = Mage::getModel('csmarketplace/vendor')
											->getCollection()
											->addAttributeToSelect('*')
											->addAttributeToFilter('status',array('eq'=>Ced_CsMarketplace_Model_Vendor::VENDOR_APPROVED_STATUS));

$entityTypeId  = $this->_vendor->getEntityTypeId();
		$setIds = Mage::getResourceModel('eav/entity_attribute_set_collection')
				->setEntityTypeFilter($entityTypeId)->getAllIds();
				
		$groupCollection = Mage::getResourceModel('eav/entity_attribute_group_collection');
		if(count($setIds) > 0) {
			$groupCollection->addFieldToFilter('attribute_set_id',array('in'=>$setIds));
		}
		if(version_compare(Mage::getVersion(), '1.6', '<')) {
			$groupCollection->getSelect()->order('main_table.sort_order');
		}
		else{
			$groupCollection->setSortOrder()->load();
		}
		
		$vendor_info = $this->_vendor->load($this->getVendorId());
		$total = 0;
		$saved = 0;
		foreach($groupCollection as $group){
			$attributes = $this->_vendor->getAttributes($group->getId(), true);
			if (count($attributes)==0) {
				continue;
			}
			foreach ($attributes as $attr){
				$attribute = Mage::getModel('csmarketplace/vendor_attribute')->load($attr->getId());
				 if($attribute->getIsVisible()){
					$total++;
					if($vendor_info->getData($attr->getAttributeCode())){
						$saved++;
					} 
				}				
			}
		}
		$this->_totalattr = $total;
		$this->_savedattr = $saved;	
$groupCollection=$groupCollection;


?>

<div class="box-right">
    <!--Account Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Seller Information') ?></h4>
            <div class="tools"><?php echo $this->getAccountEditLink()?></div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
<?php $order_id=$this->getRequest()->getParam('order_id');
$model=Mage::getModel('sales/order')->getCollection()->addFieldToFilter('entity_id', $order_id)->getData();
$inc=$model[0]['increment_id'];
$count_vendr=Mage::getModel('csmarketplace/vorders')->getCollection();

?>
		<?php foreach ($count_vendr as $vendor):
if($vendor->getOrderId()==$inc){

$vendor_info = $this->_vendor->load($vendor->getVendorId());

?>

                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Vendor Name') ?></label></td>
                    <td class="value">
                    <h3 class="product-name"><?php echo $vendor_info->getName(); ?></h3>
                    </td>
                </tr>
 <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Vendor Public Name') ?></label></td>
                    <td class="value">
                    <h3 class="product-name"><a href="<?php echo $vendor_info->getVendorShopUrl() ?>" title="<?php echo $vendorNameStripped; ?>"><?php echo $vendor_info->getPublicName(); ?></a></h3>
                    </td>
                </tr>
<?php 
foreach($groupCollection as $group) {
			$attributes = $this->_vendor->getAttributes($group->getId(), true);
foreach ($attributes as $attr){
				$attribute = Mage::getModel('csmarketplace/vendor_attribute')->setStoreId(0)->load($attr->getid());

			if($attribute->getUseInInvoice()==1){
					$html .= '<strong>'.$attr->getFrontend()->getLabel().':</strong>';
					$html .='<span class="attribute-value">'. $vendor_info->getData($attr->getAttributeCode()).'</span><br/>';?>
<tr>
                    <td class="label"><label><?php echo $attr->getFrontend()->getLabel(); ?></label></td>
                    <td class="value">
                    <h3 class="product-name"><?php echo $vendor_info->getData($attr->getAttributeCode()); ?></h3>
                    </td>
                </tr>
<?php
			}
		}
	}
}?>
                <?php endforeach;?>
                </table>
            </div>
        </div>
    </div>
</div>
