<?php
/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category  Ced
  * @package   Ced_Mobiconnectcheckout
  * @author    CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
?>
<?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
<?php $completeClass = $this->getCheckout()->getStepData('shipping', 'complete') ? 'complete' : ''; ?>
<dt class="<?php echo $completeClass ?>">
    <?php echo $this->__('Shipping Address') ?> <span class="changelink"><span class="separator">|</span> <a
        href="#payment"
        onclick="checkout.changeSection('opc-shipping');return false;"><?php echo $this->__('Change') ?></a></span>
</dt>
<dd class="<?php echo $completeClass ?>">
    <?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
    <address><?php echo $this->getShipping()->format('html') ?></address>
    <?php endif; ?>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Shipping Address') ?>
</dt>
<?php endif; ?>

